import './enum.dart';

class Countries extends Enum<String>{
  static const AE = const Countries('ae');
  static const AR = const Countries('ar');
  static const AT = const Countries('at');
  static const AU = const Countries('au');
  static const BE = const Countries('be');
  static const BG = const Countries('bg');
  static const BR = const Countries('br');
  static const CA = const Countries('ca');
  static const CH = const Countries('ch');
  static const CN = const Countries('cn');
  static const CO = const Countries('co');
  static const CU = const Countries('cu');
  static const CZ = const Countries('cz');
  static const DE = const Countries('de');
  static const EG = const Countries('eg');
  static const FR = const Countries('fr');
  static const GB = const Countries('gb');
  static const GR = const Countries('gr');
  static const HK = const Countries('hk');
  static const HU = const Countries('hu');
  static const ID = const Countries('id');
  static const IE = const Countries('ie');
  static const IL = const Countries('il');
  static const IN = const Countries('in');
  static const IT = const Countries('it');
  static const JP = const Countries('jp');
  static const KR = const Countries('kr');
  static const LT = const Countries('lt');
  static const LV = const Countries('lv');
  static const MA = const Countries('ma');
  static const MX = const Countries('mx');
  static const MY = const Countries('my');
  static const NG = const Countries('ng');
  static const NL = const Countries('nl');
  static const NO = const Countries('no');
  static const NZ = const Countries('nz');
  static const PH = const Countries('ph');
  static const PL = const Countries('pl');
  static const PT = const Countries('pt');
  static const RO = const Countries('ro');
  static const RS = const Countries('rs');
  static const RU = const Countries('ru');
  static const SA = const Countries('sa');
  static const SE = const Countries('se');
  static const SG = const Countries('sg');
  static const SI = const Countries('si');
  static const SK = const Countries('sk');
  static const TH = const Countries('th');
  static const TR = const Countries('tr');
  static const TW = const Countries('tw');
  static const UA = const Countries('ua');
  static const US = const Countries('us');
  static const VE = const Countries('ve');
  static const ZA = const Countries('za');

  const Countries(String value) : super(value);
}
